# when recursing, enters infinite loop. might be in the while(true) in the "call" switch
# it is in that while(true), namely in the else where the function isnt found in the current scope

fn test(n) {
    print(-n)
    if n {
        print(99)
        test(n - 1)
    }
}

test(10)